#!/usr/bin/env python3
"""Unattended sweep over subtraction-term configurations.

Composes a .map from each candidate block set (write-subtraction's
compose_blocks.py), regenerates + rebuilds, runs the spike test, scores the
GENUINE modes, and prints a ranked table. Turns "is this block set
better?" from a manual regenerate-build-run-read cycle into one command.

Why it exists: reasoning narrows the candidate space but does not empty
it, and the remaining choices (which S,b1, which iterated family, which
absorption order, which coefficient) are cheap to test and expensive to
argue about. A sweep also PROVES a negative — if no configuration in the
declared space scores better, the missing piece is a line form that is
not in the master at all, which is a different (and much more useful)
conclusion than "I tried some things".

THE SCORING RULE, and why it is what it is
------------------------------------------
Two properties are load-bearing, and getting either wrong makes the
sweep's negative result worthless — it reports "nothing worked" for a
space that contained the answer:

1. **The verdict is the MEDIAN, taken across the whole x scan.** A mode
   passes when its median sits at 1 and STAYS there as x decreases; one
   x landing on 1 decides nothing. So every x line of a mode is parsed
   and judged, not just the first.

2. **Outlier counts are NOT part of the verdict.** An antenna is
   spin-averaged, so a gluon-parent cluster only agrees with the matrix
   element after azimuthal averaging, and the harness averages over just
   `n_azim` orientations. A fully CORRECT term therefore reads 45-50%
   outliers on precisely those modes (run-spike-test's reference
   baseline). Scoring outliers as pass/fail systematically demotes
   correct configurations on the modes where the physics is hardest, and
   the ranking ends up measuring `n_azim` rather than the term. They are
   reported as a separate column and used ONLY to break ties between
   configurations — which is valid because `n_azim` is fixed across a
   sweep.

The deepest x is allowed to fall off the plateau when three or more x
values are present: collinear modes set a cluster mass `em = sqrts*x`
and so probe `s_ij/s ~ x**2`, which at x=1e-8 is already at double
precision. That is roundoff, not the term — but it is FLAGGED, never
silently dropped.

Usage
  # explicit block sets, one per line, "label<TAB>blk,blk,..." on stdin
  compose_blocks.py enumerate master.map --fixed Sa --axes absorb,sb1 \\
    | scan_blocks.py --master master.map --out <TERM>.map \\
        --regen "bash .../regen_rebuild.sh -n 13 -l RR -s src/process/P -t test/process/P -m checkNtoM" \\
        --run   "./checkNtoM 1 1 80 60 2" --run-cwd test/process/P \\
        --genuine 4,8,13,14 --results scan.txt

  scan_blocks.py --selftest

Options
  --genuine     comma list of GENUINE mode numbers, or the word `auto` to
                take them from the `[GENUINE]` tags the check program
                prints in its own mode banners (programs generated by
                write-spike-test's gen_spike_test.py do this). `auto` is
                preferred: the numbering then comes from the same output
                being scored, so it cannot drift from the program's
                ordering the way a hand-transcribed list does.
  --tol         |median-1| tolerance for "exact" (default 1e-4), applied
                at EVERY x of the plateau
  --near        |median-1| tolerance for "near" (default 0.10)
  --keep        directory for the per-combination raw outputs

Three harness lessons are baked in, because each cost a debugging round:
  * the loop is synchronous — never poll with `pgrep -f <this script>`,
    which matches the poller's own command line and never terminates;
  * ranking parses the score fields as integers — never `sort` on a
    line whose first field is "[12]";
  * a mode's verdict needs the whole x scan and ignores outlier counts
    (see THE SCORING RULE above) — the two mistakes that make a sweep
    silently reject correct configurations.
"""
import argparse
import os
import re
import subprocess
import sys

MODE = re.compile(r"^\s*mode\s+(\d+)\s*:(.*)$")
XLINE = re.compile(r"x=\s*(\S+).*?med=\s*(\S+).*?outl=\s*(\d+)")
NPTS = re.compile(r"\bn=\s*(\d+)")
GENTAG = re.compile(r"\[\s*GENUINE\s*\]", re.I)


def parse_run(text):
    """-> ({mode: [(x, median, outliers, npts), ...]}, {modes tagged GENUINE})

    ALL x lines of a mode are kept, in printed order (shallowest first,
    matching the check program's `do ix=ilow,iup` with x(1) > x(2) > x(3)).
    The pass criterion is a PLATEAU across that scan, so a single x cannot
    decide a mode and the list must stay intact.

    A repeated `mode N:` banner RESETS that mode's list, so concatenated
    logs score the most recent run rather than a blend of runs.
    """
    scans, tagged, cur = {}, set(), None
    for ln in text.splitlines():
        m = MODE.match(ln)
        if m:
            cur = int(m.group(1))
            scans[cur] = []
            if GENTAG.search(m.group(2)):
                tagged.add(cur)
            continue
        m = XLINE.search(ln)
        if m and cur is not None:
            try:
                med = float(m.group(2))
            except ValueError:
                med = float("nan")
            try:
                outl = int(m.group(3))
            except ValueError:
                outl = -1
            n = NPTS.search(ln)
            scans[cur].append(
                (m.group(1), med, outl, int(n.group(1)) if n else 0))
    return scans, tagged


def plateau_slice(scan):
    """The x points the verdict is taken on.

    With 3+ points the DEEPEST x may be unstable from roundoff (collinear
    modes probe s_ij/s ~ x**2), so the plateau is judged on the shallower
    ones and the deepest is flagged instead. With 1 or 2 points there is
    no plateau evidence to spare, so every point must hold.
    """
    return scan[:-1] if len(scan) >= 3 else scan


def mode_verdict(scan, tol, near_tol):
    """-> (verdict, flag); verdict in {'exact', 'near', 'bad'}.

    Outlier counts deliberately play no part — see THE SCORING RULE.
    """
    if not scan:
        return "bad", "no x lines parsed"
    judged = plateau_slice(scan)
    devs = [abs(md - 1.0) for _, md, _, _ in judged]
    if any(d != d for d in devs):                    # NaN median
        return "bad", "NaN median"
    flag = ""
    if len(scan) == 1:
        flag = "single x — no plateau evidence"
    elif len(scan) >= 3 and abs(scan[-1][1] - 1.0) >= tol:
        flag = f"deepest x ({scan[-1][0]}) off plateau, med={scan[-1][1]:g}"
    worst = max(devs)
    if worst < tol:
        return "exact", flag
    if worst < near_tol:
        return "near", flag
    return "bad", flag


def score(res, genuine, tol, near_tol):
    """-> (exact, near, bad, flags) over the genuine modes.

    `flags` maps mode -> a human-readable caveat (deepest-x instability,
    single-x scan, absent mode). Caveats never change the verdict; they
    exist so the plateau rule's escape is REPORTED rather than silent.
    """
    exact, near, bad, flags = [], [], [], {}
    buckets = {"exact": exact, "near": near, "bad": bad}
    for k in sorted(genuine):
        if k not in res:
            bad.append(k)
            flags[k] = "mode absent from output"
            continue
        verdict, flag = mode_verdict(res[k], tol, near_tol)
        buckets[verdict].append(k)
        if flag:
            flags[k] = flag
    return exact, near, bad, flags


def outlier_frac(res, genuine):
    """Mean outlier fraction over the genuine modes at the shallowest x.

    A TIEBREAKER, never a verdict. At fixed n_azim it is comparable
    ACROSS configurations, which is the only comparison it supports: a
    correct term still reads 45-50% here on gluon-parent modes, so its
    absolute value says nothing about correctness.
    """
    tot = pts = 0
    for k in genuine:
        scan = res.get(k)
        if not scan:
            continue
        _, _, outl, n = scan[0]
        if n > 0 and outl >= 0:
            tot += outl
            pts += n
    return (tot / pts) if pts else float("nan")


def run(cmd, cwd=None):
    p = subprocess.run(cmd, shell=True, cwd=cwd, capture_output=True,
                       text=True)
    return p.returncode, p.stdout + p.stderr


def selftest():
    """Structural only — encodes no physics and runs no build."""
    def xline(x, med, outl, n=100):
        return (f"   x= {x} n= {n} nan= 0 max|ME|= 1.0E+05 med= {med} "
                f"min= 1.00E+00 max= 1.00E+00 outl= {outl:>3}")

    sample = "\n".join([
        # plateau holds; only the DEEPEST x drifts -> exact, but flagged
        " mode 4: a,b soft [GENUINE] ",
        xline("1.0E-07", "1.000000", 0),
        xline("1.0E-08", "1.000000", 0),
        xline("1.0E-09", "0.700000", 40),
        " mode 5: c||d [dead] ",
        xline("1.0E-07", "0.500000", 9),
        # perfect plateau, heavy outliers -> EXACT (azimuthal average)
        " mode 6: e||f [GENUINE] ",
        xline("1.0E-07", "1.000000", 45),
        xline("1.0E-08", "1.000000", 42),
        xline("1.0E-09", "1.000000", 40),
        # good at the FIRST x, then drifts away -> BAD
        " mode 7: g soft [GENUINE] ",
        xline("1.0E-07", "1.000000", 0),
        xline("1.0E-08", "1.400000", 30),
        xline("1.0E-09", "1.900000", 60),
        # stable but off by 3% -> near
        " mode 8: h||i [GENUINE] ",
        xline("1.0E-07", "1.030000", 4),
        xline("1.0E-08", "1.030000", 4),
        xline("1.0E-09", "1.030000", 4),
    ])
    res, tagged = parse_run(sample)

    # every x line is retained, in printed order (shallowest first)
    assert len(res[4]) == 3, res[4]
    assert res[4][0][0] == "1.0E-07" and res[4][-1][0] == "1.0E-09"
    assert res[4][0][3] == 100, "point count n= not parsed"
    assert tagged == {4, 6, 7, 8}, tagged

    ex, ne, bad, flags = score(res, [4, 6, 7, 8], 1e-4, 0.10)
    assert ex == [4, 6], ex
    assert ne == [8], ne
    assert bad == [7], bad

    # REGRESSION GUARD 1: outliers must never demote a mode. A correct
    # term reads 45-50% outliers on gluon-parent modes; the old scorer
    # required outl == 0 for "exact" and so ranked such terms below
    # wrong ones.
    assert 6 in ex, "outlier count demoted a mode with a perfect plateau"

    # REGRESSION GUARD 2: the verdict needs the whole scan. The old
    # scorer read only the FIRST x line, which called mode 7 exact.
    assert 7 in bad, "a mode that drifts off the plateau passed on its first x"

    # the plateau escape is reported, not silent
    assert 4 in flags and "deepest x" in flags[4], flags
    # a mode whose whole scan sits on the plateau carries no caveat
    assert 6 not in flags, flags

    # a genuine mode absent from the output counts as bad, never exact
    ex2, _, bad2, fl2 = score(res, [4, 99], 1e-4, 0.10)
    assert ex2 == [4] and bad2 == [99], (ex2, bad2)
    assert "absent" in fl2[99]

    # a single-x scan is judged on that point but flagged as thin
    one = {1: [("1.0E-07", 1.0, 0, 50)]}
    ex3, _, _, fl3 = score(one, [1], 1e-4, 0.10)
    assert ex3 == [1] and "single x" in fl3[1], fl3

    # with exactly two points there is no spare evidence: both must hold
    two = {1: [("1.0E-07", 1.0, 0, 50), ("1.0E-08", 1.5, 0, 50)]}
    _, _, bad4, _ = score(two, [1], 1e-4, 0.10)
    assert bad4 == [1], "two-point scan let the deeper x off"

    # NaN median is bad, not silently 1
    nanres = {1: [("1.0E-07", float("nan"), 0, 50)]}
    _, _, bad5, _ = score(nanres, [1], 1e-4, 0.10)
    assert bad5 == [1], "NaN median did not fail"

    # outlier fraction is a tiebreaker and is computed, not ignored
    frac = outlier_frac(res, [4, 6])
    assert abs(frac - 0.225) < 1e-9, frac

    # ranking is numeric, not lexicographic ("10" must beat "9")
    rows = [("a", 9, 0, 0.1), ("b", 10, 0, 0.9)]
    rows.sort(key=lambda r: (-r[1], -r[2], r[3]))
    assert rows[0][0] == "b", "ranking is lexicographic"
    # ... and outliers break ties only AFTER exact/near
    rows = [("hi-outl", 10, 0, 0.5), ("lo-outl", 10, 0, 0.1)]
    rows.sort(key=lambda r: (-r[1], -r[2], r[3]))
    assert rows[0][0] == "lo-outl", "outlier tiebreak not applied"

    print("scan_blocks selftest OK")


def main():
    if "--selftest" in sys.argv:
        selftest()
        return
    ap = argparse.ArgumentParser()
    ap.add_argument("--master", required=True)
    ap.add_argument("--out", required=True,
                    help="path the composed .map is written to")
    ap.add_argument("--regen", required=True)
    ap.add_argument("--run", required=True)
    ap.add_argument("--run-cwd", default=None)
    ap.add_argument("--regen-cwd", default=None)
    ap.add_argument("--genuine", default="",
                    help="comma list of mode numbers, or `auto` to read the "
                         "[GENUINE] tags from the check program's own output")
    ap.add_argument("--tol", type=float, default=1e-4)
    ap.add_argument("--near", type=float, default=0.10)
    ap.add_argument("--results", default="scan_results.txt")
    ap.add_argument("--keep", default=None)
    ap.add_argument("--modes-spec", default="", help=argparse.SUPPRESS)
    args = ap.parse_args()

    if args.modes_spec:
        raise SystemExit(
            "ERROR: --modes-spec cannot work and has been removed. "
            "genuine_modes.py classifies mode FAMILIES, not your check "
            "program's mode NUMBERING, so it can never supply this list. "
            "Use --genuine auto (reads the program's own [GENUINE] tags) "
            "or pass an explicit comma list.")

    auto = args.genuine.strip().lower() == "auto"
    if auto:
        genuine = None                    # fixed from the first scored run
    elif args.genuine.strip():
        genuine = [int(s) for s in args.genuine.split(",") if s.strip()]
    else:
        raise SystemExit(
            "ERROR: give --genuine <list> or --genuine auto.\n"
            "  Mode NUMBERS must match your check program's own ordering. "
            "genuine_modes.py (write-spike-test) classifies FAMILIES, not "
            "that numbering, so it cannot supply this list; `auto` reads "
            "the [GENUINE] tags the generated check program prints.")

    here = os.path.dirname(os.path.abspath(__file__))
    mb = os.path.normpath(os.path.join(
        here, "..", "..", "write-subtraction", "scripts", "compose_blocks.py"))
    combos = []
    for ln in sys.stdin:
        ln = ln.rstrip("\n")
        if not ln.strip():
            continue
        label, _, blocks = ln.partition("\t")
        combos.append((label.strip(), (blocks or label).strip()))
    if not combos:
        raise SystemExit("ERROR: no combinations on stdin")

    if args.keep:
        os.makedirs(args.keep, exist_ok=True)
    rows = []
    with open(args.results, "w") as fh:
        for i, (label, blocks) in enumerate(combos, 1):
            tag = f"[{i}/{len(combos)}] {label}"
            rc, _ = run(f"{sys.executable} {mb} compose {args.master} "
                        f"--blocks '{blocks}' -o {args.out}")
            if rc:
                fh.write(f"COMPOSE-FAIL  {label}  ||  {blocks}\n"); fh.flush()
                print(f"{tag}  COMPOSE-FAIL", flush=True); continue
            rc, log = run(args.regen, cwd=args.regen_cwd)
            if rc:
                fh.write(f"REGEN-FAIL    {label}  ||  {blocks}\n"); fh.flush()
                print(f"{tag}  REGEN-FAIL", flush=True); continue
            rc, out = run(args.run, cwd=args.run_cwd)
            if args.keep:
                with open(os.path.join(args.keep, f"run_{i}.txt"), "w") as g:
                    g.write(out)
            res, tagged = parse_run(out)
            if genuine is None:
                if not tagged:
                    raise SystemExit(
                        "ERROR: --genuine auto, but the run output carries no "
                        "[GENUINE] tags. Older hand-written check programs do "
                        "not tag their modes — pass an explicit list, or "
                        "regenerate the program with gen_spike_test.py.")
                genuine = sorted(tagged)
                print(f"--genuine auto -> {len(genuine)} modes: "
                      f"{','.join(map(str, genuine))}", flush=True)
            ex, ne, bad, flags = score(res, genuine, args.tol, args.near)
            frac = outlier_frac(res, genuine)
            rows.append((label, blocks, len(ex), len(ne), len(bad), frac))
            fh.write(f"EXACT {len(ex):>3}/{len(genuine)}  NEAR {len(ne):>3}  "
                     f"BAD {len(bad):>3}  OUTL {frac:6.1%}  ||  {label}  "
                     f"||  {blocks}\n")
            for k in sorted(flags):
                fh.write(f"      mode {k}: {flags[k]}\n")
            fh.flush()
            print(f"{tag}  exact={len(ex)} near={len(ne)} bad={len(bad)} "
                  f"outl={frac:.1%}", flush=True)

    # exact, then near, then the LOWEST outlier fraction as a tiebreaker
    rows.sort(key=lambda r: (-r[2], -r[3], r[5]))
    print(f"\n=== ranked ({len(rows)} scored, {len(genuine or [])} genuine "
          f"modes) ===")
    print(f"{'EXACT':>5} {'NEAR':>5} {'BAD':>4} {'OUTL':>7}   configuration")
    for label, blocks, e, n, b, frac in rows:
        print(f"{e:>5} {n:>5} {b:>4} {frac:>7.1%}   {label or blocks}")
    print("\nVerdict is the MEDIAN across the x scan. OUTL is reported for "
          "tie-breaking only:\na correct term reads 45-50% on gluon-parent "
          "modes at small n_azim.")
    if rows and genuine and rows[0][2] < len(genuine):
        print("\nNo configuration reached all genuine modes. Within the "
              "declared space this is a NEGATIVE RESULT: the missing piece "
              "is a line form absent from the master, not a subset of it. "
              "Next step is measurement (probe-me-ir-structure), not more "
              "searching.")


if __name__ == "__main__":
    main()
