#!/usr/bin/env python3
"""Pole scan of an antenna function (or any Fortran expression) over ALL
infrared limits of a phase space: the antenna's POLE GRAPH.

Usage:  python antenna_probe.py spec.json > polescan_gen.f
        python antenna_probe.py --selftest

Given an antenna call, a process init block and a parton multiplicity,
emit a Fortran program that drives phase space into every 2-parton and
3-parton collinear limit and every single/double soft limit in turn and
prints, per limit and per x, the MEDIAN of |s^p * antenna| for
p = 0, 1, 2 (median, not mean: single deep points dominate a mean and
make the output unreadable).

Reading the output = the pole graph:
  - collinear modes: s is the vanishing invariant (s_ij or s_ijk,
    normalised by sqrts^2). The pole power in that limit is the smallest
    p for which median|s^p * A| stays stable as x decreases. This
    reading is independent of the harness's x parametrisation.
  - soft modes: no single invariant vanishes (the eikonal has product
    poles); s is replaced by the scan parameter x itself, so the column
    to read is the fitted exponent alpha = -dlog10(median|A|)/dlog10(x).
Everything else — the colour chain, which slots are radiators, which
are unresolved — follows mechanically from which limits are singular.

Spec fields:
  process     : init_proc name, e.g. "epem"
  sqrts       : e.g. 1000.0
  init_kin    : [npartons, arg2] as in the process's check program
  npar        : kinematics-set index = total momenta (5..8), e.g. 7
  fs_partons  : final-state momentum indices, e.g. [3,4,5,6,7]
  decl_lines  : verbatim DECLARATION lines (common blocks) — may be []
  setup_lines : verbatim EXECUTABLE init lines — may be []
  target      : the antenna call (kinematics index included), e.g.
                "FullB40(3,4,5,6,7)" — any Fortran expression works
  xs_list     : x scan, e.g. [1e-5, 1e-6, 1e-7] (>= 3 recommended:
                enables the built-in consistency self-check)
  npt         : points per (mode, x), e.g. 100
  families    : optional subset of ["ss","sco","ds","tc"]; default all
                that the multiplicity supports (npar=5: ss/sco only)
  azimuthal   : optional, default true — average target over a rotp
                pi/2 rotation in collinear modes (kills spin-correlation
                oscillations; harmless when absent)
  cuts_call   : optional verbatim cuts call (default: none — a bare
                antenna needs no jet cuts)
"""
import itertools
import json
import sys

FAM_ID = {"ss": 1, "sco": 2, "ds": 3, "tc": 4}


def modes_for(fs, families):
    """Mechanical mode table for the given final-state partons."""
    out = []  # (family, unresolved tuple, spectators tuple, name)
    fsset = set(fs)
    if "ss" in families:
        for i in fs:
            out.append(("ss", (i,), tuple(sorted(fsset - {i})),
                        f"{i} soft"))
    if "sco" in families:
        for i, j in itertools.combinations(fs, 2):
            out.append(("sco", (i, j), tuple(sorted(fsset - {i, j})),
                        f"{i}||{j} coll"))
    if "ds" in families:
        for i, j in itertools.combinations(fs, 2):
            out.append(("ds", (i, j), tuple(sorted(fsset - {i, j})),
                        f"{i},{j} soft"))
    if "tc" in families:
        for i, j, k in itertools.combinations(fs, 3):
            out.append(("tc", (i, j, k), tuple(sorted(fsset - {i, j, k})),
                        f"{i}||{j}||{k} coll"))
    return out


def gen_call(fam, npar, u, sp):
    args = {"ss": list(u) + ["em1"] + list(sp),
            "sco": list(u) + ["em1"] + list(sp),
            "ds": list(u) + ["em1"] + list(sp),
            "tc": list(u) + ["em1"] + list(sp)}[fam]
    astr = ",".join(str(a) for a in args)
    return f"call get_{fam}{npar}(sqrts_proc,{astr})"


def em_expr(fam):
    # conventions of the check-program suite (write-spike-test skill)
    return ("em1=sqrts_proc*dsqrt(1d0-xs)" if fam in ("ss", "ds")
            else "em1=sqrts_proc*xs")


def s_expr(fam, npar, u):
    if fam == "sco":
        return f"abs(s{npar}({u[0]},{u[1]}))/sqrts_proc**2"
    if fam == "tc":
        return (f"(abs(s{npar}({u[0]},{u[1]}))+abs(s{npar}({u[0]},{u[2]}))"
                f"+abs(s{npar}({u[1]},{u[2]})))/sqrts_proc**2")
    return "xs"  # soft families: scan-parameter proxy (see module docstring)


HDR = """      program polescan_gen
c     generated by antenna_probe.py -- see probe-me-ir-structure skill
      use Process_mod
      use KinData_mod
      use Scales_mod
      use Mapping_mod
      implicit real*8(a-h,o-y)
      implicit complex*16(z)
      common/plotmode/iplot
      parameter (nxs={nxs})
      parameter (npt={npt})
      dimension xslist(nxs)
      dimension va0(npt), va1(npt), va2(npt)
      dimension amed(nxs), alph(nxs)
{decls}

      call init_proc("{process}")
      call init_map()
      call setSqrts_proc({sqrts}d0)
      iplot=2
      call setScales()
      call init_kin({ik0},{ik1})
"""

MODE_HEAD = """
c     ---- mode {imode}: {name} ----
      write(*,*)
      write(*,*) 'mode: {name}'
      do ix=1,nxs
        xs = xslist(ix)
        nacc = 0
        do ii=1,npt
          {em}
          {gen}
          ipass=1
{cuts}          a = {target}
{azim}          if (a.ne.a) cycle
          sv = {sexpr}
          nacc = nacc + 1
          va0(nacc) = abs(a)
          va1(nacc) = abs(sv*a)
          va2(nacc) = abs(sv*sv*a)
        end do
        if (nacc.lt.3) then
          write(*,'(a,es9.1,a)') '   x=', xs, '  too few accepted points'
          amed(ix) = 0d0
          cycle
        end if
        call pmedian(va0,nacc,em0)
        call pmedian(va1,nacc,em1m)
        call pmedian(va2,nacc,em2m)
        amed(ix) = em0
        write(*,'(a,es9.1,a,i5,3(a,es12.4))') '   x=', xs,
     .    '  n=', nacc, '  med|A|=', em0, '  med|sA|=', em1m,
     .    '  med|s2A|=', em2m
      end do
      call slopes(xslist,amed,nxs,alph,nsl)
      if (nsl.ge.1) write(*,'(a,8f8.2)')
     .    '   exponent alpha(|A|~x^-alpha): ', (alph(i),i=1,nsl)
      if (nsl.ge.2) then
        if (abs(alph(1)-alph(nsl)).lt.0.3d0) then
          write(*,*) '  selfcheck: consistent across x'
        else
          write(*,*) '  selfcheck: INCONSISTENT across x -- do not'
          write(*,*) '  trust this mode (cuts? too-shallow x? NaNs?)'
        end if
      end if
"""

AZIM = """          call rotp{npar}({i},{j})
          a2 = {target}
          if (a2.eq.a2) a = 0.5d0*(a+a2)
"""

CUTS = """          {cuts_call}
          if (ipass.ne.1) cycle
"""

TAIL = """
      call destroy_kin()
      stop
      end program polescan_gen

************************************************************************
*     median of v(1:n) (insertion sort on a copy)
************************************************************************
      subroutine pmedian(v,n,res)
      implicit real*8(a-h,o-z)
      dimension v(n), w(100000)
      do i=1,n
        w(i)=v(i)
      end do
      do i=2,n
        t=w(i)
        j=i-1
        do while (j.ge.1)
          if (w(j).le.t) exit
          w(j+1)=w(j)
          j=j-1
        end do
        w(j+1)=t
      end do
      if (mod(n,2).eq.1) then
        res=w((n+1)/2)
      else
        res=0.5d0*(w(n/2)+w(n/2+1))
      end if
      return
      end

************************************************************************
*     log-log slopes between consecutive x values
************************************************************************
      subroutine slopes(xs,ym,n,al,nsl)
      implicit real*8(a-h,o-z)
      dimension xs(n), ym(n), al(n)
      nsl=0
      do i=1,n-1
        if (ym(i).le.0d0 .or. ym(i+1).le.0d0) cycle
        nsl=nsl+1
        al(nsl) = -(log10(ym(i+1))-log10(ym(i)))
     .            /(log10(xs(i+1))-log10(xs(i)))
      end do
      return
      end
"""


def f77(lines, indent="      "):
    return "\n".join(indent + ln if ln.strip() else ln for ln in lines)


def generate(spec):
    npar = spec["npar"]
    fs = spec["fs_partons"]
    default_fams = ["ss", "sco"] + (["ds", "tc"] if npar >= 6 else [])
    families = spec.get("families", default_fams)
    if npar == 5:
        families = [f for f in families if f in ("ss", "sco")]
    modes = modes_for(fs, families)
    if not modes:
        raise ValueError("empty mode table")
    xs = spec["xs_list"]
    target = spec["target"]
    azim = spec.get("azimuthal", True)
    cuts = spec.get("cuts_call")

    out = HDR.format(nxs=len(xs), npt=spec["npt"], process=spec["process"],
                     sqrts=spec["sqrts"], ik0=spec["init_kin"][0],
                     ik1=spec["init_kin"][1],
                     decls=f77(spec.get("decl_lines", [])))
    out += f77(spec.get("setup_lines", [])) + "\n"
    xsdata = ", ".join(f"{x:.1e}".replace("e", "d") for x in xs)
    out += f"\n      data xslist / {xsdata} /\n"

    for imode, (fam, u, sp, name) in enumerate(modes, 1):
        az = ""
        if azim and fam in ("sco", "tc"):
            az = AZIM.format(npar=npar, i=u[0], j=u[1], target=target)
        ct = CUTS.format(cuts_call=cuts) if cuts else ""
        out += MODE_HEAD.format(imode=imode, name=name, em=em_expr(fam),
                                gen=gen_call(fam, npar, u, sp),
                                cuts=ct, target=target, azim=az,
                                sexpr=s_expr(fam, npar, u))
    out += TAIL
    return out


def selftest():
    """Structural self-test — encodes NO expected physics answer. Checks
    the mode-table combinatorics and the well-formedness of the emitted
    Fortran; the numerical consistency check (scanner agreeing with
    itself across two x values) is built into the generated program."""
    from math import comb
    for npar, fs in ((6, [3, 4, 5, 6]), (7, [3, 4, 5, 6, 7])):
        n = len(fs)
        m = modes_for(fs, ["ss", "sco", "ds", "tc"])
        counts = {}
        for fam, u, sp, _ in m:
            counts[fam] = counts.get(fam, 0) + 1
            assert len(u) + len(sp) == n, "unresolved+spectators != fs"
            assert not set(u) & set(sp), "overlap unresolved/spectators"
        assert counts["ss"] == comb(n, 1)
        assert counts["sco"] == comb(n, 2)
        assert counts["ds"] == comb(n, 2)
        assert counts["tc"] == comb(n, 3)
        spec = {"process": "p", "sqrts": 100.0, "init_kin": [n, 10],
                "npar": npar, "fs_partons": fs,
                "decl_lines": [], "setup_lines": ["continue"],
                "target": "dummy_ant(3,4,5)", "xs_list": [1e-5, 1e-6, 1e-7],
                "npt": 10}
        src = generate(spec)
        assert src.count("'mode: ") == len(m), "one print per mode"
        assert src.count(f"call get_ss{npar}") == counts["ss"]
        assert src.count(f"call get_tc{npar}") == counts["tc"]
        for ln in src.splitlines():
            assert not ("a = dummy_ant" in ln and "c " in ln[:2]), \
                f"fused comment/statement: {ln!r}"
        assert "end program polescan_gen" in src
    print("antenna_probe selftest OK")


def main():
    if len(sys.argv) > 1 and sys.argv[1] == "--selftest":
        selftest()
        return
    spec = json.load(open(sys.argv[1]))
    sys.stdout.write(generate(spec))


if __name__ == "__main__":
    main()
