#!/usr/bin/env python3
"""Emit a Fortran IR-structure probe from a short JSON spec.

Usage:  python gen_probe.py spec.json > probe_gen.f

Spec fields (see example_spec.json):
  process        : init_proc name, e.g. "epem"
  sqrts          : e.g. 1000.0
  init_kin       : [npartons, arg2], e.g. [5, 10]
  decl_lines     : verbatim DECLARATION lines (common blocks, logicals)
                   — emitted before any executable statement.
  setup_lines    : verbatim EXECUTABLE lines (flavour settings, jet
                   parameters, masses) — copy from the process's check
                   program; MUST leave iplot nonzero.
  mode           : "soft" | "collinear"
  em_expr        : e.g. "sqrts_proc*dsqrt(1d0-xs)"  (soft)
                   or   "sqrts_proc*xs"             (collinear)
  limit_call     : verbatim, e.g.
                   "call get_ss7(sqrts_proc,4,em1,3,5,6,7)"
  cuts_call      : verbatim, e.g. "call ecuts_epem(1,7,ipass)"
  full_me        : verbatim expression, e.g. "C1g0Z(3,4,5,6,7,2,1)"
  xs_list        : x values to scan, e.g. [1e-8, 1e-9, 1e-10]
  npt            : points per x, e.g. 400
  # soft mode: single shared map + reduced ME, basis = antennae only
  soft_map       : verbatim set_map call
  soft_redme     : verbatim expression using j1..j9
  basis          : list of entries:
     soft:      {"label": "(3,5)", "antenna": "FullA30FF(3,4,5,7)"}
     collinear: {"label": "...", "antenna": "...",
                 "map": "call set_map(...)", "redme": "..."}
"""
import json
import sys

HDR = """      program probe_gen
c     generated by gen_probe.py -- see probe-me-ir-structure skill
      use Process_mod
      use KinData_mod
      use Scales_mod
      use Mapping_mod
      implicit real*8(a-h,o-y)
      implicit complex*16(z)
      common/plotmode/iplot
      parameter (nb={nb})
      parameter (nxs={nxs})
      dimension b({nb}), am({nb},{nb}), rhs({nb}), c({nb})
      dimension xslist({nxs})
      logical degen
{decls}

      call init_proc("{process}")
      call init_map()
      call setSqrts_proc({sqrts}d0)
      iplot=2
      call setScales()
      call init_kin({ik0},{ik1})
"""

LOOP_HEAD = """
      data xslist / {xsdata} /

      do ix=1,nxs
        xs = xslist(ix)
        am  = 0d0
        rhs = 0d0
        nacc = 0
        do ii=1,{npt}
          em1={em_expr}
          {limit_call}
          ipass=1
          {cuts_call}
          if (ipass.ne.1) cycle
          ame = {full_me}
"""

SOFT_POINT = """          call unset_map()
          ipass=1
          {soft_map}
          if (ipass.ne.1) cycle
          red = {soft_redme}
          if (abs(red).lt.1d-30) cycle
          y = ame/red
{basis_eval}
"""

COLL_POINT = """          y = ame
{basis_eval}
"""

ACCUM = """c         normalise per point so no single deep point dominates
          scal = 0d0
          do kk=1,nb
            scal = scal + b(kk)**2
          end do
          if (scal.lt.1d-300) cycle
          scal = 1d0/scal
          do kk=1,nb
            do ll=1,nb
              am(kk,ll) = am(kk,ll) + scal*b(kk)*b(ll)
            end do
            rhs(kk) = rhs(kk) + scal*b(kk)*y
          end do
          nacc = nacc + 1
        end do

        write(*,*)
        write(*,*) 'x = ', xs, '  accepted points: ', nacc
        call gsolve(am,rhs,c,nb,degen,resid)
        if (degen) then
          write(*,*) 'DEGENERATE SYSTEM (rank < nb):'
          write(*,*) 'refusing coefficients. Only coefficient SUMS'
          write(*,*) 'over degenerate directions are determined.'
          write(*,*) 'Collinear basis? Use antenna*redME entries and'
          write(*,*) 'judge stability across the x scan.'
        else
          write(*,*) 'coefficients (residual = ', resid, '):'
{basis_print}        end if
      end do

      call destroy_kin()
      stop
      end program probe_gen
"""

SOLVER = """
************************************************************************
*     Gaussian elimination with degeneracy REFUSAL (no pivot clamping)
*     and residual report. degen=.true. => do not trust x().
************************************************************************
      subroutine gsolve(a,rhs,x,n,degen,resid)
      implicit real*8(a-h,o-z)
      logical degen
      dimension a(n,n), rhs(n), x(n)
      dimension w(50,51), a0(50,50), r0(50)
      degen=.false.
      amax=0d0
      do i=1,n
        do j=1,n
          w(i,j)=a(i,j)
          a0(i,j)=a(i,j)
          if(abs(a(i,j)).gt.amax) amax=abs(a(i,j))
        end do
        w(i,n+1)=rhs(i)
        r0(i)=rhs(i)
      end do
      if(amax.lt.1d-300)then
        degen=.true.
        return
      endif
      tol = 1d-10*amax
      do k=1,n
        p=0d0
        ip=k
        do i=k,n
          if(abs(w(i,k)).gt.p)then
            p=abs(w(i,k))
            ip=i
          endif
        end do
        do j=k,n+1
          t=w(k,j)
          w(k,j)=w(ip,j)
          w(ip,j)=t
        end do
        if(abs(w(k,k)).lt.tol) then
          degen=.true.
          return
        endif
        do i=k+1,n
          f=w(i,k)/w(k,k)
          do j=k,n+1
            w(i,j)=w(i,j)-f*w(k,j)
          end do
        end do
      end do
      do i=n,1,-1
        s=w(i,n+1)
        do j=i+1,n
          s=s-w(i,j)*x(j)
        end do
        x(i)=s/w(i,i)
      end do
      resid=0d0
      do i=1,n
        s=-r0(i)
        do j=1,n
          s=s+a0(i,j)*x(j)
        end do
        resid=resid+s*s
      end do
      resid=dsqrt(resid)
      return
      end
"""


def f77(lines, indent="      "):
    return "\n".join(indent + ln if ln.strip() else ln for ln in lines)


def generate(spec):
    basis = spec["basis"]
    nb = len(basis)
    xs = spec["xs_list"]
    mode = spec["mode"]
    # "target" is the general name: any Fortran expression to be fitted —
    # a full ME (the original use) OR an antenna function (residue fitting:
    # what does an X40 reduce to on this boundary?). "full_me" kept as an
    # accepted synonym for old specs.
    target = spec.get("target", spec.get("full_me"))
    if target is None:
        raise KeyError("spec needs 'target' (or legacy 'full_me')")

    out = HDR.format(nb=nb, nxs=len(xs), process=spec["process"],
                     sqrts=spec["sqrts"], ik0=spec["init_kin"][0],
                     ik1=spec["init_kin"][1],
                     decls=f77(spec.get("decl_lines", [])))
    out += f77(spec.get("setup_lines", [])) + "\n"

    xsdata = ", ".join(f"{x:.1e}".replace("e", "d") for x in xs)
    out += LOOP_HEAD.format(xsdata=xsdata, npt=spec["npt"],
                            em_expr=spec["em_expr"],
                            limit_call=spec["limit_call"],
                            cuts_call=spec["cuts_call"],
                            full_me=target)

    if mode == "soft":
        beval = []
        for k, e in enumerate(basis, 1):
            beval.append(f"          b({k}) = {e['antenna']}")
        out += SOFT_POINT.format(soft_map=spec["soft_map"],
                                 soft_redme=spec["soft_redme"],
                                 basis_eval="\n".join(beval))
    else:  # collinear / residue mode: basis element = antenna [* reduced ME]
        beval = []
        for k, e in enumerate(basis, 1):
            if "map" in e:  # basis term evaluated on its own mapped momenta
                beval.append("          call unset_map()")
                beval.append("          ipass=1")
                beval.append(f"          {e['map']}")
                beval.append("          if (ipass.ne.1) cycle")
            if "redme" in e:
                beval.append(
                    f"          b({k}) = ({e['antenna']})*({e['redme']})")
            else:  # pure antenna-basis entry (antenna-on-antenna residue fit)
                beval.append(f"          b({k}) = {e['antenna']}")
        out += COLL_POINT.format(basis_eval="\n".join(beval))

    bprint = ""
    for k, e in enumerate(basis, 1):
        lbl = e.get("label", f"basis {k}")
        bprint += (f"          write(*,'(a,f16.8)') '   {lbl} : ', c({k})\n")
    out += ACCUM.format(basis_print=bprint)
    out += SOLVER
    return out


def selftest():
    """Structural self-test. Encodes NO physics answer: it only checks that
    the emitted Fortran is well-formed (the historical failure was the last
    basis assignment fused onto the following comment line)."""
    base = {
        "process": "p", "sqrts": 100.0, "init_kin": [3, 10],
        "decl_lines": ["common /x/ ndum"], "setup_lines": ["ndum=1"],
        "em_expr": "sqrts_proc*xs",
        "limit_call": "call get_sco5(sqrts_proc,3,4,em1,5)",
        "cuts_call": "continue",
        "target": "dummy_target(3,4,5)",
        "xs_list": [1e-5, 1e-6], "npt": 10,
    }
    soft = dict(base, mode="soft",
                soft_map="call set_map(5,4,(/3,4/),(/1,2,3,5/),ipass)",
                soft_redme="dummy_red(j1,j2,j3)",
                basis=[{"label": "t1", "antenna": "f1(3,4,5)"},
                       {"label": "t2", "antenna": "f2(3,4,5)"}])
    coll = dict(base, mode="collinear",
                basis=[{"label": "t1", "antenna": "f1(3,4,5)",
                        "map": "call set_map(5,4,(/3,4/),(/1,2,3,5/),ipass)",
                        "redme": "r1(j1,j2,j3)"},
                       {"label": "t2", "antenna": "f2(3,4,5)"}])
    for name, sp in (("soft", soft), ("collinear", coll)):
        src = generate(sp)
        for ln in src.splitlines():
            # no executable statement fused with a comment line
            assert not ("b(" in ln and "normalise" in ln), \
                f"{name}: fused basis/comment line: {ln!r}"
            # fixed-form comments must start in column 1
            if "normalise per point" in ln:
                assert ln.startswith("c"), f"{name}: comment not col 1: {ln!r}"
        # every basis assignment present, on its own line
        n_assign = sum(1 for ln in src.splitlines()
                       if ln.strip().startswith("b(") and "=" in ln)
        assert n_assign == 2, f"{name}: expected 2 basis lines, {n_assign}"
        assert src.splitlines()[0].strip() == "program probe_gen"
        assert "end program probe_gen" in src
    print("gen_probe selftest OK")


def main():
    if len(sys.argv) > 1 and sys.argv[1] == "--selftest":
        selftest()
        return
    spec = json.load(open(sys.argv[1]))
    sys.stdout.write(generate(spec))


if __name__ == "__main__":
    main()
