#!/usr/bin/env python3
"""Mode 4 — z-differential residue profile in a COLLINEAR limit.

Why a fourth mode. The least-squares residue fitter (gen_probe.py, mode
3) cannot answer "what does this bare ANTENNA reduce to in a collinear
limit": every basis entry carries the same 1/s_ij pole, so the design
matrix collapses to rank 1 and only the coefficient SUM is determined.
The documented cure — basis entries as antenna x reduced ME — works only
when the TARGET is a matrix element, because it is the reduced MEs that
lift the degeneracy. With a bare antenna there is nothing to lift it, and
the solver returns unstable, non-rational numbers that look like a
physics answer and are not one.

The cure is a different measurement, not a better solver: do not solve,
PROFILE. Bin the points by the collinear momentum fraction z and report

    median( target / candidate )   per z-bin, with its spread

for each candidate separately. Reading it:
  * ratio FLAT in z and rational        -> candidate is the right object,
                                           the constant is its coefficient;
  * ratio flat but irrational           -> right species, wrong normalisation
                                           or a missing partner term;
  * ratio VARIES with z                 -> wrong species, or the candidate
                                           mixes soft and collinear pieces
                                           the target weights differently
                                           (the signature that a sub-antenna
                                           split is needed, not a coefficient);
  * spread within a bin large           -> azimuthal terms survive; the
                                           profile averages over a rotp
                                           pi/2 rotation by default, so a
                                           residual spread means the parent
                                           is a gluon and the candidate has
                                           the wrong spin structure.

z is measured from invariants, z = s(i,r)/(s(i,r)+s(j,r)) with r a hard
spectator, which tends to the momentum fraction at leading power and is
reference-independent there.

Usage:
  residue_profile.py spec.json > profile_gen.f
  residue_profile.py --selftest

Spec fields (same conventions as gen_probe.py / antenna_probe.py):
  process, sqrts, init_kin, npar, decl_lines, setup_lines
  limit_call : verbatim collinear driver, e.g.
               "call get_sco7(sqrts_proc,3,4,em1,5,6,7)"
  em_expr    : default "sqrts_proc*xs"
  coll       : [i, j]  the collinear pair (for z and the rotp average)
  zref       : hard spectator index used for z (default: first non-pair
               final-state index appearing in limit_call)
  target     : Fortran expression, e.g. "E40bb(3,6,5,4,7)"
  candidates : [{"label": "...", "expr": "FullA30FF(3,4,5,7)*FullE30FF(3,6,5,7)"}]
  xs_list    : default [1e-6, 1e-7, 1e-8]   (see the cutoff guidance in
               run-spike-test: look for a plateau, expect deep-x noise)
  npt        : points per x (default 400)
  nbins      : z bins (default 8)
  cuts_call  : optional; a bare antenna profile needs no jet cuts
  azimuthal  : default true
"""
import json
import sys

HDR = """      program profile_gen
c     generated by residue_profile.py -- probe-me-ir-structure mode 4
      use Process_mod
      use KinData_mod
      use Scales_mod
      use Mapping_mod
      implicit real*8(a-h,o-y)
      implicit complex*16(z)
      common/plotmode/iplot
      parameter (nzb={nbins})
      parameter (ncnd={ncand})
      parameter (mx={npt})
      dimension acc(nzb,ncnd,mx), nacc(nzb,ncnd)
      dimension cand(ncnd)
      dimension xslist({nxs})
      character*40 clab(ncnd)
{decls}

      call init_proc("{process}")
      call init_map()
      call setSqrts_proc({sqrts}d0)
      iplot=2
      call setScales()
      call init_kin({ik0},{ik1})
{setup}
{labels}
      data xslist / {xsdata} /

      do ix=1,{nxs}
        xs = xslist(ix)
        acc  = 0d0
        nacc = 0
        ntot = 0
        do ii=1,mx
          em1={em_expr}
          {limit_call}
          ipass=1
{cuts}
          if (ipass.ne.1) cycle
          tgt = {target}
{cand_eval}
{azim}
c         z from invariants: leading-power momentum fraction
          sir = kin({npar})%s({ci},{zref})
          sjr = kin({npar})%s({cj},{zref})
          if (abs(sir+sjr).lt.1d-300) cycle
          zz = sir/(sir+sjr)
          ib = int(zz*nzb)+1
          if (ib.lt.1) ib=1
          if (ib.gt.nzb) ib=nzb
          ntot = ntot+1
          do k=1,ncnd
            if (abs(cand(k)).lt.1d-300) cycle
            r = tgt/cand(k)
            if (r.ne.r) cycle
            if (nacc(ib,k).ge.mx) cycle
            nacc(ib,k) = nacc(ib,k)+1
            acc(ib,k,nacc(ib,k)) = r
          end do
        end do

        write(*,*)
        write(*,'(a,es9.1,a,i6,a)') ' x= ',xs,'   (',ntot,' points)'
        do k=1,ncnd
          write(*,'(a,a)') '   candidate: ',clab(k)
          write(*,'(a)') '     z-bin        n     median      spread'
          do ib=1,nzb
            if (nacc(ib,k).lt.3) then
              write(*,'(a,f5.2,a,i6,a)') '     ',(ib-0.5d0)/nzb,
     .          ' ',nacc(ib,k),'   (too few points)'
              cycle
            end if
            call pmed(acc(ib,k,1),nacc(ib,k),rmed,rspr)
            write(*,'(a,f5.2,a,i6,2x,f12.6,2x,es10.2)') '     ',
     .        (ib-0.5d0)/nzb,' ',nacc(ib,k),rmed,rspr
          end do
        end do
      end do

      call destroy_kin()
      stop
      end program profile_gen

************************************************************************
      subroutine pmed(v,n,rmed,rspr)
c     median and a robust spread (half the 16-84 percentile range)
      implicit real*8(a-h,o-z)
      dimension v(n), w({npt})
      do i=1,n
        w(i)=v(i)
      end do
      do i=2,n
        t=w(i)
        j=i-1
        do while (j.ge.1)
          if (w(j).le.t) exit
          w(j+1)=w(j)
          j=j-1
        end do
        w(j+1)=t
      end do
      if (mod(n,2).eq.1) then
        rmed=w((n+1)/2)
      else
        rmed=0.5d0*(w(n/2)+w(n/2+1))
      end if
      i16=max(1,int(0.16d0*n))
      i84=min(n,max(1,int(0.84d0*n)))
      rspr=0.5d0*(w(i84)-w(i16))
      return
      end
"""


def emit(spec):
    cands = spec.get("candidates") or []
    if not cands:
        raise SystemExit("ERROR: spec needs at least one entry in 'candidates'")
    coll = spec.get("coll")
    if not coll or len(coll) != 2:
        raise SystemExit("ERROR: spec needs 'coll': [i, j] (the collinear pair)")
    npar = spec.get("npar", 7)
    ci, cj = coll
    zref = spec.get("zref")
    if zref is None:
        import re
        nums = [int(t) for t in re.findall(r"\b(\d+)\b", spec["limit_call"])]
        cands_ref = [n for n in nums if n not in (ci, cj) and 3 <= n <= npar]
        if not cands_ref:
            raise SystemExit("ERROR: cannot infer 'zref'; set it explicitly")
        zref = cands_ref[-1]
    xs = spec.get("xs_list", [1e-6, 1e-7, 1e-8])
    npt = int(spec.get("npt", 400))
    nbins = int(spec.get("nbins", 8))
    decls = "\n".join("      " + s for s in spec.get("decl_lines", []))
    setup = "\n".join("      " + s for s in spec.get("setup_lines", []))
    labels = "\n".join(
        f"      clab({k+1}) = '{c.get('label', 'cand%d' % (k+1))[:40]}'"
        for k, c in enumerate(cands))
    ce = "\n".join(f"          cand({k+1}) = {c['expr']}"
                   for k, c in enumerate(cands))
    azim = ""
    if spec.get("azimuthal", True):
        azim = (f"          call rotp{npar}({ci},{cj})\n"
                f"          tgt = 0.5d0*(tgt + {spec['target']})\n"
                + "\n".join(
                    f"          cand({k+1}) = 0.5d0*(cand({k+1}) + {c['expr']})"
                    for k, c in enumerate(cands)))
    cuts = ("          " + spec["cuts_call"]) if spec.get("cuts_call") else ""
    return HDR.format(
        nbins=nbins, ncand=len(cands), npt=npt, nxs=len(xs),
        decls=decls, setup=setup, labels=labels,
        process=spec["process"], sqrts=spec.get("sqrts", 1000.0),
        ik0=spec["init_kin"][0], ik1=spec["init_kin"][1],
        xsdata=", ".join(f"{v:.8e}".replace("e", "d") for v in xs),
        em_expr=spec.get("em_expr", "sqrts_proc*xs"),
        limit_call=spec["limit_call"], cuts=cuts,
        target=spec["target"], cand_eval=ce, azim=azim,
        npar=npar, ci=ci, cj=cj, zref=zref)


def selftest():
    """Structural only: checks emitted-code shape, encodes no physics."""
    spec = {
        "process": "PROC", "sqrts": 1000.0, "init_kin": [5, 10], "npar": 7,
        "decl_lines": ["common /koppel/ nf,nc,b0"], "setup_lines": ["nf=5"],
        "limit_call": "call get_sco7(sqrts_proc,3,4,em1,5,6,7)",
        "coll": [3, 4], "target": "XT(3,6,5,4,7)",
        "candidates": [{"label": "c1", "expr": "XA(3,4,5,7)*XB(3,6,5,7)"},
                       {"label": "c2", "expr": "XA(3,4,7,7)*XB(3,6,5,7)"}],
        "xs_list": [1e-6, 1e-7], "npt": 50, "nbins": 4,
    }
    f = emit(spec)
    for need in ("iplot=2", 'call init_proc("PROC")', "call init_kin(5,10)",
                 "call get_sco7", "XT(3,6,5,4,7)", "call pmed",
                 "parameter (nzb=4)", "parameter (ncnd=2)", "call rotp7(3,4)"):
        assert need in f, f"missing from emitted program: {need}"
    # both candidates evaluated and both labelled
    assert "cand(1) = XA(3,4,5,7)" in f and "cand(2) = XA(3,4,7,7)" in f
    assert "clab(1) = 'c1'" in f and "clab(2) = 'c2'" in f
    # z uses the pair and an inferred hard reference that is neither
    assert "%s(3,7)" in f and "%s(4,7)" in f, "z estimator wrong slots"
    # azimuthal averaging can be switched off
    g = emit(dict(spec, azimuthal=False))
    assert "rotp7" not in g, "azimuthal average not disabled"
    # explicit zref honoured
    h = emit(dict(spec, zref=5))
    assert "%s(3,5)" in h and "%s(4,5)" in h
    # refusals
    for bad, why in ((dict(spec, candidates=[]), "no candidates"),
                     ({k: v for k, v in spec.items() if k != "coll"},
                      "no coll")):
        try:
            emit(bad)
            raise AssertionError(f"accepted spec with {why}")
        except SystemExit:
            pass
    print("residue_profile selftest OK")


if __name__ == "__main__":
    if "--selftest" in sys.argv:
        selftest()
    else:
        sys.stdout.write(emit(json.load(open(sys.argv[1]))))
